%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: OrberApp_IFR
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ORBERAPP_IFR_HRL).
-define(ORBERAPP_IFR_HRL, true).




-endif.


