%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PushConsumer
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PUSHCONSUMER_HRL).
-define(COSEVENTCOMM_PUSHCONSUMER_HRL, true).




-endif.


