%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_HRL).
-define(OE_COSEVENTCOMM_HRL, true).




-endif.


