%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_TIO
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_TIO_HRL).
-define(COSTIME_TIO_HRL, true).




-endif.


