%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTime
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTIME_HRL).
-define(OE_COSTIME_HRL, true).




-endif.


