%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: m_i
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(M_I_HRL).
-define(M_I_HRL, true).




-endif.


