%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventDomainAdmin_EventDomainFactory
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTDOMAINADMIN_EVENTDOMAINFACTORY_HRL).
-define(COSEVENTDOMAINADMIN_EVENTDOMAINFACTORY_HRL, true).




-endif.


