%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_VirtualFileSystem
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_VIRTUALFILESYSTEM_HRL).
-define(COSFILETRANSFER_VIRTUALFILESYSTEM_HRL, true).




-endif.


