%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_HRL).
-define(COSNOTIFYCOMM_HRL, true).


-record('CosNotifyComm_InvalidEventType', {'OE_ID'="IDL:omg.org/CosNotifyComm/InvalidEventType:1.0", type}).


-endif.


