%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotification_AdminPropertiesAdmin
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosNotification/src/CosNotification.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFICATION_ADMINPROPERTIESADMIN_HRL).
-define(COSNOTIFICATION_ADMINPROPERTIESADMIN_HRL, true).




-endif.


