%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_FixedProperty
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_FixedProperty').
-ic_compiled("4_2_30").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/FixedProperty:1.0",
                   "FixedProperty",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/FixedProperty:1.0".

%% returns name
name() -> "CosPropertyService_FixedProperty".



