%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_UnsupportedFilterableData
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_UnsupportedFilterableData').
-ic_compiled("4_2_30").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/UnsupportedFilterableData:1.0",
                   "UnsupportedFilterableData",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/UnsupportedFilterableData:1.0".

%% returns name
name() -> "CosNotifyFilter_UnsupportedFilterableData".



