%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_NotConnected
%% Source: /net/isildur/ldisk/daily_build/r15b01_prebuild_opu_o.2012-04-01_20/otp_src_R15B01/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.30
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_NotConnected').
-ic_compiled("4_2_30").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/NotConnected:1.0",
                   "NotConnected",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/NotConnected:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_NotConnected".



